services:
  backend:
    # swap sha-${GITHUB_SHA} to latest to deploy elsewhere
    # this is for github actions and a vps
    image: ghcr.io/lachlanmacphee/thebetterhandbook:sha-${GITHUB_SHA}
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - network
    env_file:
      - .env

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
        read_only: true
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config:

networks:
  network:
    driver: bridge
