services:
  backend:
    image: ghcr.io/lachlanmacphee/thebetterhandbook:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./static:/usr/share/nginx/html
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config:
