version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000" # Map container port 8080 to host port 8080
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_HOST=${EMAIL_HOST}
      - SESSION_SECRET=${SESSION_SECRET}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
