# fly.toml app configuration file generated for thebetterhandbook on 2025-04-14T15:02:59+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thebetterhandbook'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
